language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
script: yarn build # Here you could also run the build step of your application
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --regions bru --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: false
      all_branches: true
  - provider: script
    script: now --regions bru --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN && now rm bet-with-goodall --safe --yes --token $NOW_TOKEN 
    skip_cleanup: true
    on:
      master: true
